In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

<center>  

# **Introdução à programação em Python**  

<br>  

</center>

---

## **2) Manipulação de arquivo**

> O arquivo é  um **conjunto de dados** digitalizados que pode ser gravado em um dispositivo de armazenamento e tratado como ente único.

### **2.1) Criando e abrindo arquivos .txt**

> Para criar e abrir podemos utilizaro metodo **open ( )** , dessa forma iremos abrir com um parametro determinado, de acordo com o modo de uso

> Para escrever dentro do arquivo vamos utilizar o método **write ( )**, que recebe uma string como parâmetro e a insere no arquivo.

![Captura de tela 2023-07-11 082639.png]()

In [ ]:
nome_arquivo = 'arquivo_escrita.txt'
conteudo_para_anexar = 'Trainee de Programação Básica em Python - Lapisco'

with open(nome_arquivo, 'a') as arquivo:
    arquivo.write(conteudo_para_anexar)

In [ ]:
nome_arquivo = 'arquivo_escrita.txt'
conteudo_para_escrever = 'Trainee de Programação Básica em Python - Lapisco - 2ª aula'

with open(nome_arquivo, 'w') as arquivo:
    arquivo.write(conteudo_para_escrever)

###**2.2) Lendo arquivos**

> Para fazer a leitura os dados que os arquivos possuem , vamos utilizar dois métodos, primeiro **readline ( )**, que lê a quantidade N de caracteres da primeira linha passadas com parâmetro. E o segundo é o **readlines ( )** que retorna todas linhas.

In [ ]:
nome_arquivo = 'arquivo_leitura1.txt'
conteudo_para_anexar = 'Trainee de Programação Básica em Python - Lapisco'

with open(nome_arquivo, 'a') as arquivo:
    arquivo.write(conteudo_para_anexar)

with open(nome_arquivo, 'r') as arquivo:
    conteudo_atualizado = arquivo.readline(10)

print(conteudo_atualizado)

Trainee de

In [ ]:
nome_arquivo = 'arquivo_leitura2.txt'
conteudo_para_anexar = 'Trainee de Programação Básica em Python - Lapisco'

with open(nome_arquivo, 'a') as arquivo:
    arquivo.write(conteudo_para_anexar)

with open(nome_arquivo, 'r') as arquivo:
    conteudo_atualizado = arquivo.readlines()

print(conteudo_atualizado)

['Trainee de Programação Básica em Python - Lapisco']

### **2.3)Manipulaçã de arquivos .csv e .xlsx**

> Para manipular arquivos de tais extensões precisamos das bibliotecas numpy e pandas.

### **2.3.1) Criando arquivos .csv e .xlsx**

> Para criar esse arquivos vamos precisar das libs csv e openyxl, depois vamos criar utilizando o mesmo método anterior **open ( )**. Escrevendo utilizando o método **writer ( )**.

In [ ]:
# Para arquivos .csv's
import pandas as pd

dados = {
    'Nome': ['João', 'Maria'],
    'Idade': [25, 30],
    'Cidade': ['São Paulo', 'Rio de Janeiro']
}

df = pd.DataFrame(dados)

In [ ]:
# Para arquivos .xlsx
import pandas as pd
data = {
    'Nome': ['João', 'Maria', 'Carlos', ''],
    'Idade': [25, 28, 22, 23],
    'Cargo': ['Analista', 'Gerente', 'Estagiário', '']
}

workbook = pd.DataFrame(data)

### **2.3.2) Salvar arquivos .csv e .xlsx**

> Para salvar podemos utilizar **.to_'extensão do arquivo' ( )**

In [ ]:
from google.colab import files
import pandas as pd

df.to_csv('/content/drive/MyDrive/Trainee_Lapisco/df.csv', index=False)

In [ ]:
from google.colab import files
import pandas as pd

workbook.to_excel('/content/drive/MyDrive/Trainee_Lapisco/exemplo.xlsx', index=False)

### **2.3.3) Leitura de arquivos .csv e .xlsx**

> Para fazer a leitura desse arquivos podemos utiliza a funçãi **pandas.read_csv ( )** para ler arquivos csv, ou **pandas.read_excel ( )** para ler arquivos do Excel

In [ ]:
import pandas as pd
import numpy as np

new_df = pd.read_csv('/content/drive/MyDrive/Trainee_Lapisco/df.csv')
new_df

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     30  Rio de Janeiro

In [ ]:
import pandas as pd
import numpy as np

new_table = pd.read_excel('/content/drive/MyDrive/Trainee_Lapisco/exemplo.xlsx')
new_table

     Nome  Idade       Cargo
0    João     25    Analista
1   Maria     28     Gerente
2  Carlos     22  Estagiário
3     NaN     23         NaN

### **2.3.4) Manipulação de arquivos**

> Para a munipulação de arquivos temos vários comandos, mas vou listar os mais usados :
 - `.head()`
 - `.tail()`
 - `.describe()`
 - `.shape()`
 - `.dtypes()`
 - `.loc()`
 - `.iloc()`
 - `.sort_values()`
 - `.isnul()`

> No método **head ( )** como seguimos ver uma quantidade N de dados de uma tebla, contando de cima para baixo

In [ ]:
# Exemplo com head
new_df.head(1)

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     30  Rio de Janeiro

> No método **tail ( )** como seguimos ver uma quantidade N de dados de uma tebla, contando de baixo para cima

In [ ]:
# Exemplo com tail
new_df.tead(1)

> No método **decribe ( )** ele decreve todos os dados presentes, criando uma linha para count (conta a quantidade de dados), mean (dá media dos valores), std(dá o desvio padrão), min (dá o minimo valor dos dados), 25%, 50%, 75% (representam os valores em repectivas porcentagens), max( máximo valor presente)

In [ ]:
# Exemplo com describe
new_df.describe()

           Idade
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

> No método **shape ( )**  mostra o tamenho da nossa tabela em x e y

In [ ]:
# Exemplo com shape
new_df.shape

(2, 3)

> No método **dtypes ( )** mostra o tipo de objeto que a coluna recebe

In [ ]:
# Exemplo com dtypes
new_df.dtypes

Nome      object
Idade      int64
Cidade    object
dtype: object

> No método **loc ( )** permite acessar o DataFrame a partir do nome, acessando pelo índice da linha ou coluna.

In [ ]:
# Exemplo com loc
new_df.loc[(new_df['Nome'] == 'João')]

   Nome  Idade     Cidade
0  João     25  São Paulo

> O metodo **iloc ( )**  permite você acessar um DataFrame a partir do índice da linha e da coluna. Recebendo valor inteiro(int) para acessar a linha ou coluna.

In [ ]:
# Exemplo com iloc
new_table.iloc[1:2]

    Nome  Idade    Cargo
1  Maria     28  Gerente

> O metodo **sort_values ( )**  ordena os registros com base em uma ou mais colunas do seu DataFrame, permitindo escolhar a forma de ordenção.

In [ ]:
# Exemplo com sort_values
new_table.sort_values(by=['Nome'])

     Nome  Idade       Cargo
2  Carlos     22  Estagiário
0    João     25    Analista
1   Maria     28     Gerente
3     NaN     23         NaN

> O metodo **isnull ( )**  usados para verificar e gerenciar valores NULL em um dataframe.

In [ ]:
# Exemplo com isnull
new_table.isnull()

    Nome  Idade  Cargo
0  False  False  False
1  False  False  False
2  False  False  False
3   True  False   True

# - - -